ROOT := test10menhir_with_aux
OCAMLBUILD_PACKAGES := pprint
OTTFLAGS := -aux_style_rules false -generate_aux_rules true
QUOTIENTED_PDF_OTTFLAGS := -quotient_rules true -generate_aux_rules false
UNQUOTIENTED_PDF_OTTFLAGS := -quotient_rules false -generate_aux_rules false -aux_style_rules false

include ../common.mk
