ROOT := test_if
MENHIR_EXTRA_MLY = $(OTTDIR)/menhir/menhir_library_extra.mly
MENHIRFLAGS := --infer --explain --unused-tokens --trace --base $(ROOT)_parser
OCAMLBUILD_PACKAGES := pprint

include ../common.mk
